[default]
src = 'src'
out = 'out'
libs = ['lib']

[rpc_endpoints]
goerli = "https://eth-goerli.g.alchemy.com/v2/lizUvVnXmrcdSRvHLgTTCcpoQ_nASY8X"

# goerli = "https://goerli.infura.io/v3/e5f57e3684bf43068b71f7a25887cd46"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config